### ISSUE TITLE
Store codes and locations

### ISSUE THREAD

**Issue by dylan-klomparens** [LordExodius/ikea#1]
The online version of this IKEA stock checker is super helpful. Thank you for creating this project. Using your work, I was able to expand the program's search capability to the United States. I noticed you were looking for the list of store codes and their corresponding locations. See the list below. I found this list by going to the [store locator web page](https://www.ikea.com/us/en/stores/). The store ID is shown when you hover the mouse over a pin on the map. I used this to compile the complete list.

I've also attached a modified version of your program (slightly simplified) that works for the US. Please feel free to use it or merge it to your code if you desire.

Thanks again for the super helpful project. Hopefully we can all find our IKEA items soon!

`locations = {
	"488": "Renton, WA",
	"028": "Portland, OR",
	"157": "West Sacramento, CA",
	"165": "Emeryville, CA",
	"347": "East Palo Alto, CA",
	"462": "Las Vegas, NV",
	"399": "Burbank, CA",
	"413": "Covina, CA",
	"162": "Carson, CA",
	"167": "Costa Mesa, CA",
	"209": "Tempe, AZ",
	"166": "San Diego, CA",
	"103": "Draper, UT",
	"064": "Centennial, CO",
	"570": "Live Oak, TX",
	"379": "Houston, TX",
	"027": "Round Rock, TX",
	"535": "Grand Prairie, TX",
	"183": "Frisco, TX",
	"508": "Memphis, TN",
	"374": "Merriam, KS",
	"212": "Twin Cities, MN",
	"410": "St. Louis, MO",
	"560": "Oak Creek, WI",
	"210": "Schaumburg, IL",
	"170": "Bolingbrook, IL",
	"536": "Fishers, IN",
	"026": "Canton, MI",
	"175": "West Chester, OH",
	"511": "Columbus, OH",
	"153": "Pittsburgh, PA",
	"067": "Charlotte, NC",
	"257": "Atlanta, GA",
	"537": "Jacksonville, FL",
	"145": "Orlando, FL",
	"042": "Tampa, FL",
	"207": "Sunrise, FL",
	"327": "Miami, FL",
	"569": "Norfolk, VA",
	"158": "Stoughton, MA",
	"168": "Woodbridge, VA",
	"411": "College Park, MD",
	"152": "Baltimore, MD",
	"215": "South Philadelphia, PA",
	"211": "Conshohocken, PA",
	"154": "Elizabeth, NJ",
	"921": "Brooklyn, NY",
	"622": "Queens, NY",
	"156": "Long Island, NY",
	"409": "Paramus, NJ",
	"213": "New Haven, CT",
}`

[Modified version of your code](https://github.com/LordExodius/ikea/files/8052605/main.txt)

**Comment by LordExodius** [comment]
Hey, thank you so much! Glad to hear someone's found this little project useful :^)

I've been a bit busy with school, but I'll try to find some time in the next few weeks to patch these new locations and possibly some other countries into the online version - hopefully with a better interface too. Appreciate the updated code and tips.

**Comment by LordExodius** [comment]
Okay, all implemented! Summary of relevant changes as follows:

1. Merged Canadian and US list of stores into an SQLite database so there isn't a big ugly dictionary sitting at the top of the program. Also easier to add stores in the future by updating the DB rather than providing new code.
2. Simplified main code structure. I reread the JSON and realized some of the checks were unnecessary or made things more complicated than necessary, so there's one less indent layer now.

Thanks for the list and the modified code as well, both were very helpful for this quick update.
